### ISSUE TITLE
Segfault, keeps crashing

### ISSUE THREAD

**Issue by Dorian-DS** [getsolus/brisk-menu#12]
Browsing menu causes random crashes with a popup option of reloading the menu.

Reloading works, eventually crashes again.

Stock MATE, no changes at all.

dmesg shows this error
`Brisk-menu[926]: segfault at 7fb6dc0008d0 ip 00007fb6dc0008d0 sp 00007ffe51ac1418 error 15`

Cannot find other logs for brisk-menu.

**Comment by kyrios123** [comment]
Which version of MATE are you using?

**Comment by ScionLinux** [comment]
Version 1.20.4

> Which version of MATE are you using?

1.20.4
