### ISSUE TITLE
Update to README suggestion

### ISSUE THREAD

**Issue by jradxl** [getsolus/brisk-menu#17]
Hello,
When someone is next editing the README, could I suggest the following additions....
In the Building section:-
1. Add a comment to direct reader to download the ***.tar.xz from releases.
Alas, I went straight to the Download button and understand now why it didn't build.
2. Add a comment to direct reader to also download brisk-menu-translations to ensure updatePot.sh works. Don't know whether this is needed for a build, but I did it anyway.

I was building in isolation on Fedora 31 Mate Spin, as it is not included.
Works fine!
Thanks
John

**Comment by kyrios123** [comment]
Heum heum... read the text **right above** the download assets. Impossible to make it more visible.

> Note to Packagers: Please use the release tarball rather than the GitHub auto-generated tarball. Ours includes the necessary git submodule / translations needed.
