### ISSUE TITLE
Meson Build

### ISSUE THREAD

**Issue by xotan135** [getsolus/brisk-menu#19]
The Meson build system
Version: 0.51.2
Source dir: /home/xxx/Downloads/brisk-menu-master
Build dir: /home/xxx/Downloads/brisk-menu-master/build
Build type: native build
Project name: brisk-menu
Project version: 0.6.1
C compiler for the host machine: cc (gcc 9.2.0 "cc (Gentoo 9.2.0-r2 p3) 9.2.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Program meson_post_install.sh found: YES (/home/john/Downloads/brisk-menu-master/meson_post_install.sh)
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Run-time dependency gtk+-3.0 found: YES 3.24.10
Run-time dependency gio-unix-2.0 found: YES 2.60.6
Run-time dependency gdk-x11-3.0 found: YES 3.24.10
Run-time dependency x11 found: YES 1.6.9
Run-time dependency libmatepanelapplet-4.0 found: YES 1.22.1
Run-time dependency libmate-menu found: YES 1.22.0
Run-time dependency libnotify found: YES 0.7.8
Configuring config.h using configuration
Found pkg-config: /usr/bin/pkg-config (1.6.3)
Configuring com.solus_project.brisk.BriskMenu.mate-panel-applet using configuration
Configuring org.mate.panel.applet.BriskMenuFactory.service using configuration

meson.build:109:0: ERROR: Subproject exists but has no meson.build file

A full log can be found at /home/xxx
[meson-log.txt](https://github.com/getsolus/brisk-menu/files/3934621/meson-log.txt)
/Downloads/brisk-menu-master/build/meson-logs/meson-log.txt

Linux LPT00 5.4.0 #23 SMP Fri Dec 6 16:55:24 CST 2019 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux

I am having the following issue building 0.6.1. I do not have any issues building 0.6.0 though. I'm not sure what other information you would like.

**Comment by JoshStrobl** [comment]
> meson.build:109:0: ERROR: Subproject exists but has no meson.build file

You'd get this if you opt to not follow our generated dist tarballs on the releases page. Please make sure you're using our tarball and not the one generated automatically by GitHub, as per our info in bold on the release that says "Note to Packagers: Please use the release tarball rather than the GitHub auto-generated tarball. Ours includes the necessary git submodule / translations needed."
