### ISSUE TITLE
ERROR: Subproject exists but has no meson.build file

### ISSUE THREAD

**Issue by jaypatelani** [getsolus/brisk-menu#23]
when porting brisk-menu on NetBSD 8.1 amd64 i get this error and here is log :

https://termbin.com/oc54

want me to share Makefile? 

Thanks

**Comment by kyrios123** [comment]
Looks like you did not use the release tarball:

> **Note to Packagers:** Please use the release tarball rather than the GitHub auto-generated tarball. Ours includes the necessary git submodule / translations needed.
