### ISSUE TITLE
Delete applet from config error "BriskMenuFactory::BriskMenu"

### ISSUE THREAD

**Issue by jaypatelani** [getsolus/brisk-menu#24]
any documentation of how to troubleshoot applet errors and debug ?
here is screenshot of an error. 

https://i.imgur.com/7s8yyX6.png

**Comment by jaypatelani** [comment]
solved it ..Thanks

**Comment by stephematician** [comment]
@jaypatelani - how did you solve it?

**Comment by jaypatelani** [comment]
> [@jaypatelani](https://github.com/jaypatelani) - how did you solve it?

Hi. It was long ago now I don't remember 😅

**Comment by stephematician** [comment]
@jaypatelani I've opened a new issue in case it reminds you of anything: https://github.com/getsolus/brisk-menu/issues/60

**Comment by jaypatelani** [comment]
> [@jaypatelani](https://github.com/jaypatelani) I've opened a new issue in case it reminds you of anything: [#60](https://github.com/getsolus/brisk-menu/issues/60)

Last i remember I made it work with this port on NetBSD https://wip.pkgsrc.org/cgi-bin/gitweb.cgi?p=pkgsrc-wip.git;a=tree;f=briskmenu
