### ISSUE TITLE
allow removing the text next to the menu icon

### ISSUE THREAD

**Issue by gsbhasin123** [getsolus/brisk-menu#31]
Because... I know what the icon does.

**Comment by kyrios123** [comment]
Except that multiple applications can have the same icon.

**Comment by gsbhasin123** [comment]
True... but still, it should be configurable

**Comment by JoshStrobl** [comment]
I don't agree with this feature request.

**Comment by gsbhasin123** [comment]
Oh well... Which file is the code that displays "Menu" in? I can just edit that for my local copy

**Comment by vkareh** [comment]
hmmm... This feature is already in place. To hide the menu label, run this:
```
gsettings set com.solus-project.brisk-menu label-visible false
```
Or use dconf-editor and navigate to `com/solus-project/brisk-menu` and toggle the `label-visible` option.

**Comment by gsbhasin123** [comment]
Oh. It is! I didn't realize that, thank you!

**Comment by JoshStrobl** [comment]
I must've misunderstood the request. Thought it was talking about the actual desktop entries.

**Comment by gsbhasin123** [comment]
Ah, no, I was talking about the icon on the panel. Thanks anyways!

**Comment by kyrios123** [comment]
I also misunderstood... hehehe...

**Comment by gsbhasin123** [comment]
Ah, you all thought that I meant the icons next to the application names in the menu? No, I was talking about the icon on the panel. I should have been more specific, but saying icon instead of icons wasn't a typo ;)
