### ISSUE TITLE
[Feature request] Add an option to open Favorites view by default

### ISSUE THREAD

**Issue by choduram** [getsolus/brisk-menu#40]
Would be great if this was a possibility, on Debian Buster Mate.

**Comment by JoshStrobl** [comment]
But we already do this.

https://github.com/getsolus/brisk-menu/blob/master/src/frontend/menu-loader.c#L146

**Comment by choduram** [comment]
> But we already do this. Even fired up Solus MATE Edition via a live USB and confirmed, shows Favorites first.
> 
> https://github.com/getsolus/brisk-menu/blob/master/src/frontend/menu-loader.c#L146

Hi,

That's good news to me.

Sorry for creating an already existing feature request.

I'm on Debian Buster Mate, could you pl. help me understand how I can achieve this - do I need to edit a file or run something in terminal or use some menu editor, 

thank you

**Comment by JoshStrobl** [comment]
No you just need an operating system that isn't so old. Brisk Menu is 0.5.0 in buster, you need at least 0.6.0.

**Comment by choduram** [comment]
> No you just need an operating system that isn't so old. Brisk Menu is 0.5.0 in buster, you need at least 0.6.0.

Ah ok, gottcha, thank you 
https://packages.debian.org/buster/mate-applet-brisk-menu

I guess I need to find a way to manually update the package.
