### ISSUE TITLE
Activation after building brisk-menu on NetBSD 

### ISSUE THREAD

**Issue by jaypatelani** [getsolus/brisk-menu#6]
After building brisk-menu how one can activate it or start it ? Here is my logs meson-log.txt and install-log.txt 

http://termbin.com/ggex
http://termbin.com/3adu

Thanks, 
Jay

**Comment by kyrios123** [comment]
Just like any applets:
Right-click on the mate-panel -> add to panel and then search for Brisk Menu
That's it.

**Comment by jaypatelani** [comment]
Hi, 
i tried adding to panel but "brisk menu" is not shown in list. is  there a way to configure using gsettings or other way? 
Thanks

**Comment by kyrios123** [comment]
Which version of MATE are you using ?
If it's a version > 1.20, you have to build from the last commit. We haven't tagged a release for 1.22 yet.

**Comment by jaypatelani** [comment]
MATE 1.20.1 does that require new build? 
Thanks,
Jay
